force-app/main/default/objects/Account/fields/FICA_CIF_Flag__c.field-meta.xml
<CustomField>
    <fullName>FICA_CIF_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FICA CIF Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FinServ_Length_Of_Relationship__c.field-meta.xml
<CustomField>
    <fullName>FinServ_Length_Of_Relationship__c</fullName>
    <label>Length Of Relationship</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LLC_BI_Total_Direct_Exposure__c.field-meta.xml
<CustomField>
    <fullName>LLC_BI_Total_Direct_Exposure__c</fullName>
    <label>Total Direct Exposure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BB_C360_AccountService.cls
public with sharing class BB_C360_AccountService {

    public static Account getAccount(Id accountId) {
        return [
            SELECT
                Name,
                Industry,
                FICA_CIF_Flag__c,
                FinServ_Length_Of_Relationship__c,
                LLC_BI_Total_Direct_Exposure__c,
                Customer_Key__c
            FROM Account
            WHERE Id = :accountId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }
}